### ISSUE TITLE
als server not working with istio

### ISSUE THREAD

**Issue by zirain** [abhide/envoy-access-log-server#1]
hello, I want try this code with istio 1.6, and my istio cm as follow:
![image](https://user-images.githubusercontent.com/4354057/114307342-bfd3a500-9b11-11eb-85e0-d47fb067e681.png)

but I got nothing on the server, anything I missed?

**Comment by abhide** [comment]
@zirain would like to know what you were trying. Any chance you could share the configuration?

Saw you closed the issue, just curious if you could share how you got it fixed?

**Comment by zirain** [comment]
sorry to miss this message
as far as I can recall, I test with istio 1.6 which still use v2 proto.
